local _, CombatCue = ...

CombatCue.translations = {
    enUS = {
        loaded = "loaded. Type /combatcue to configure.",
        title = "CombatCue",
        tabMessages = "Messages",
        tabAppearance = "Appearance",
        tabAnimation = "Animation",
        tabPosition = "Position",
        fontSize = "Font size",
        enterCombatMessage = "Enter combat message",
        leaveCombatMessage = "Leave combat message",
        enterCombatColor = "Enter color",
        leaveCombatColor = "Leave color",
        animation = "Animation",
        animationEnabled = "Enable animation",
        animationStyle = "Style",
        animationStyleFade = "Fade",
        animationStyleScale = "Scale",
        animationStyleFlash = "Flash",
        displayDuration = "Display duration",
        animationDuration = "Effect duration",
        animationScale = "Scale intensity",
        positionX = "Position X",
        positionY = "Position Y",
        moveHint = "Move the preview text on screen to choose its position.",
        previewEnter = "Preview enter",
        previewLeave = "Preview leave",
        reset = "Reset",
        close = "Close",
    },
    frFR = {
        loaded = "charge. Tape /combatcue pour configurer.",
        title = "CombatCue",
        tabMessages = "Messages",
        tabAppearance = "Apparence",
        tabAnimation = "Animation",
        tabPosition = "Position",
        fontSize = "Taille de police",
        enterCombatMessage = "Message entree combat",
        leaveCombatMessage = "Message sortie combat",
        enterCombatColor = "Couleur entree",
        leaveCombatColor = "Couleur sortie",
        animation = "Animation",
        animationEnabled = "Activer animation",
        animationStyle = "Style",
        animationStyleFade = "Fondu",
        animationStyleScale = "Zoom",
        animationStyleFlash = "Flash",
        displayDuration = "Duree affichage",
        animationDuration = "Duree effet",
        animationScale = "Intensite zoom",
        positionX = "Position X",
        positionY = "Position Y",
        moveHint = "Deplace le texte de preview a l'ecran pour choisir sa position.",
        previewEnter = "Apercu entree",
        previewLeave = "Apercu sortie",
        reset = "Reinitialiser",
        close = "Fermer",
    },
}

CombatCue.L = setmetatable(
    CombatCue.translations[GetLocale()] or CombatCue.translations.enUS,
    { __index = CombatCue.translations.enUS }
)
